export class AvatarTranslateService {

    static traducoes = [
        //Accessories
        { texto: "accessories_blank", traducao: "Nenhum" },
        { texto: "accessories_kurta", traducao: "Óculos 1" },
        { texto: "accessories_prescription01", traducao: "Óculos 2" },
        { texto: "accessories_prescription02", traducao: "Óculos 3" },
        { texto: "accessories_round", traducao: "Óculos 4" },
        { texto: "accessories_sunglasses", traducao: "Óculos 5" },
        { texto: "accessories_wayfarers", traducao: "Óculos 6" },
        //ClothesColor
        { texto: "clothColor_black", traducao: "Preto" },
        { texto: "clothColor_blue1", traducao: "Ciano" },
        { texto: "clothColor_blue2", traducao: "Azul royal" },
        { texto: "clothColor_blue3", traducao: "Azul marinho" },
        { texto: "clothColor_gray1", traducao: "Cinza claro" },
        { texto: "clothColor_gray2", traducao: "Cinza" },
        { texto: "clothColor_heather", traducao: "Cinza escuro" },
        { texto: "clothColor_pastel_blue", traducao: "Azul pastel" },
        { texto: "clothColor_pastel_green", traducao: "Verde pastel" },
        { texto: "clothColor_pastel_orange", traducao: "Laranja pastel" },
        { texto: "clothColor_pastel_red", traducao: "Vermelho pastel" },
        { texto: "clothColor_pastel_yellow", traducao: "Amarelo pastel" },
        { texto: "clothColor_pink", traducao: "Rosa" },
        { texto: "clothColor_red", traducao: "Vermelho" },
        { texto: "clothColor_white", traducao: "Branco" },
        //Clothes
        { texto: "clothe_blazer_shirt", traducao: "Blazer com camiseta" },
        { texto: "clothe_blazer_sweater", traducao: "Blazer com suéter" },
        { texto: "clothe_collar_sweater", traducao: "Suéter" },
        { texto: "clothe_graphic_shirt", traducao: "Camiseta com estampa" },
        { texto: "clothe_hoodie", traducao: "Moletom" },
        { texto: "clothe_OVERALL", traducao: "Macação" },
        { texto: "clothe_shirt_crewneck", traducao: "Camiseta gola redonda" },
        { texto: "clothe_shirt_scoopneck", traducao: "Camiseta gola canoa" },
        { texto: "clothe_shirt_vneck", traducao: "Camiseta gola V" },
        //Eyebrow
        { texto: "eyebrow_angry", traducao: "" },
        { texto: "eyebrow_angry_natural", traducao: "" },
        { texto: "eyebrow_none", traducao: "" },
        { texto: "eyebrow_default_natural", traducao: "" },
        { texto: "eyebrow_flat_natural", traducao: "" },
        { texto: "eyebrow_raised_excited", traducao: "" },
        { texto: "eyebrow_raised_excited_natural", traducao: "" },
        { texto: "eyebrow_sad_concerned", traducao: "" },
        { texto: "eyebrow_sad_concerned_natural", traducao: "" },
        { texto: "eyebrow_unibrow_natural", traducao: "" },
        { texto: "eyebrow_updown", traducao: "" },
        { texto: "eyebrow_updown_natural", traducao: "" },
        //Eyes
        { texto: "eyes_close", traducao: "Fechados" },
        { texto: "eyes_cry", traducao: "Chorando" },
        { texto: "eyes_none", traducao: "Normal" },
        { texto: "eyes_dizzy", traducao: "Morto" },
        { texto: "eyes_eyeroll", traducao: "" },
        { texto: "eyes_happy", traducao: "Feliz" },
        { texto: "eyes_hearts", traducao: "Apaixonado" },
        { texto: "eyes_side", traducao: "" },
        { texto: "eyes_squint", traducao: "" },
        { texto: "eyes_surprised", traducao: "" },
        { texto: "eyes_wink", traducao: "Piscada 1" },
        { texto: "eyes_winkwacky", traducao: "Piscada 2" },
        //FacialHairColor
        { texto: "facialHairColor_auburn", traducao: "" },
        { texto: "facialHairColor_black", traducao: "" },
        { texto: "facialHairColor_blonde", traducao: "" },
        { texto: "facialHairColor_blonde_golden", traducao: "" },
        { texto: "facialHairColor_brown", traducao: "" },
        { texto: "facialHairColor_brown_dark", traducao: "" },
        { texto: "facialHairColor_pastel_pink", traducao: "" },
        { texto: "facialHairColor_platinum", traducao: "" },
        { texto: "facialHairColor_red", traducao: "" },
        { texto: "facialHairColor_silver_red", traducao: "" },
        // { texto: "facialHairColor_platinum", traducao: "" },
        //FacialHair
        { texto: "facialHair_BLANK", traducao: "" },
        { texto: "facialHair_beard_medium", traducao: "" },
        { texto: "facialHair_beard_light", traducao: "" },
        { texto: "facialHair_beard_magestic", traducao: "" },
        { texto: "facialHair_moustache_fancy", traducao: "" },
        { texto: "facialHair_moustache_magnum", traducao: "" },
        //Graphic 
        { texto: "graphic_bat", traducao: "" },
        { texto: "graphic_cumbia", traducao: "" },
        { texto: "graphic_ deer", traducao: "" },
        { texto: "graphic_diamond", traducao: "" },
        { texto: "graphic_hola", traducao: "" },
        { texto: "graphic_pizza", traducao: "" },
        { texto: "graphic_resist", traducao: "" },
        { texto: "graphic_selena", traducao: "" },
        { texto: "graphic_bear", traducao: "" },
        { texto: "graphic_skulloutline", traducao: "" },
        { texto: "graphic_skull", traducao: "" },
        // { texto: "graphic_ deer", traducao: "" },
        //HairColor 
        { texto: "hairColor_aurburn", traducao: "" },
        { texto: "hairColor_black", traducao: "" },
        { texto: "hairColor_blonde", traducao: "" },
        { texto: "hairColor_blondegolden", traducao: "" },
        { texto: "hairColor_brown", traducao: "" },
        { texto: "hairColor_browndark", traducao: "" },
        { texto: "hairColor_pastelpink", traducao: "" },
        { texto: "hairColor_platinum", traducao: "" },
        { texto: "hairColor_red", traducao: "" },
        { texto: "hairColor_silvergray", traducao: "" },
        //HatColor
        { texto: "hatColor_black", traducao: "" },
        { texto: "hatColor_blue01", traducao: "" },
        { texto: "hatColor_blue02", traducao: "" },
        { texto: "hatColor_blue03", traducao: "" },
        { texto: "hatColor_gray01", traducao: "" },
        { texto: "hatColor_gray02", traducao: "" },
        { texto: "hatColor_heather", traducao: "" },
        { texto: "hatColor_pastel_blue", traducao: "" },
        { texto: "hatColor_pastel_green", traducao: "" },
        { texto: "hatColor_pastel_orange", traducao: "" },
        { texto: "hatColor_pastel_red", traducao: "" },
        { texto: "hatColor_pastel_yellow", traducao: "" },
        { texto: "hatColor_pink", traducao: "" },
        { texto: "hatColor_red", traducao: "" },
        { texto: "hatColor_white", traducao: "" },
        //Mouth 
        { texto: "mouth_concerened", traducao: "" },
        { texto: "mouth_none", traducao: "" },
        { texto: "mouth_disbelief", traducao: "" },
        { texto: "mouth_eating", traducao: "" },
        { texto: "mouth_grimface", traducao: "" },
        { texto: "mouth_sad", traducao: "" },
        { texto: "mouth_scream_open", traducao: "" },
        { texto: "mouth_serious", traducao: "" },
        { texto: "mouth_smile", traducao: "" },
        { texto: "mouth_tongue", traducao: "" },
        { texto: "mouth_twinkle", traducao: "" },
        { texto: "mouth_vomit", traducao: "" },
        //Skin
        { texto: "skin_tanned", traducao: "Bronzeada" },
        { texto: "skin_yellow", traducao: "Amarela" },
        { texto: "skin_pale", traducao: "Pálida" },
        { texto: "skin_light", traducao: "Branca" },
        { texto: "skin_brown", traducao: "Marrom" },
        { texto: "skin_dark_brown", traducao: "Marrom Escura" },
        { texto: "skin_black", traducao: "Preta" },
        //Top 
        { texto: "tops_no_hair", traducao: "Careca" },
        { texto: "tops_eyepatch", traducao: "Tapa olho" },
        { texto: "tops_hat", traducao: "Chapéu" },
        { texto: "tops_hijab", traducao: "Hijabe" },
        { texto: "tops_turban", traducao: "Turbante" },
        { texto: "tops_winter_hat1", traducao: "Touca 1" },
        { texto: "tops_winter_hat2", traducao: "Touca 2" },
        { texto: "tops_winter_hat3", traducao: "Touca 3" },
        { texto: "tops_winter_hat4", traducao: "Touca 4" },
        { texto: "tops_longhair_bighair", traducao: "" },
        { texto: "tops_longhair_bob", traducao: "" },
        { texto: "tops_longhair_bun", traducao: "" },
        { texto: "tops_longhair_curly", traducao: "" },
        { texto: "tops_longhair_curvy", traducao: "" },
        { texto: "tops_longhair_dreads", traducao: "" },
        { texto: "tops_longhair_frida", traducao: "" },
        { texto: "tops_longhair_fro", traducao: "" },
        { texto: "tops_longhair_froband", traducao: "" },
        { texto: "tops_longhair_nottoolong", traducao: "" },
        { texto: "tops_longhairs_havedsides", traducao: "" },
        { texto: "tops_longhair_miawallace", traducao: "" },
        { texto: "tops_longhair_straight", traducao: "" },
        { texto: "tops_longhair_straight2", traducao: "" },
        { texto: "tops_longhair_straightstrand", traducao: "" },
        { texto: "tops_shorthair_dreads01", traducao: "" },
        { texto: "tops_shorthair_dreads02", traducao: "" },
        { texto: "tops_shorthair_frizzle", traducao: "" },
        { texto: "tops_shorthair_shaggymullet", traducao: "" },
        { texto: "tops_shorthair_shortcurly", traducao: "" },
        { texto: "tops_shorthair_shortflat", traducao: "" },
        { texto: "tops_shorthair_shortround", traducao: "" },
        { texto: "tops_shorthair_shortwaved", traducao: "" },
        { texto: "tops_shorthair_sides", traducao: "" },
        { texto: "tops_shorthair_thecaesar", traducao: "" },
        { texto: "tops_shorthair_thecaesarsidepart", traducao: "" }
    ]

    static translate(texto: string): string {
        let item = this.traducoes.find(x => x.texto == texto);
        if (item && item.traducao != "")
            return item.traducao;
        return texto;
    }
}
