export class AvatarTranslateService {

    static traducoes = [
        //Accessories
        { texto: "accessories_blank", traducao: "Nenhum" },
        { texto: "accessories_kurta", traducao: "Óculos 1" },
        { texto: "accessories_prescription01", traducao: "Óculos 2" },
        { texto: "accessories_prescription02", traducao: "Óculos 3" },
        { texto: "accessories_round", traducao: "Óculos 4" },
        { texto: "accessories_sunglasses", traducao: "Óculos 5" },
        { texto: "accessories_wayfarers", traducao: "Óculos 6" },
        //ClothesColor
        { texto: "clothColor_black", traducao: "Preto" },
        { texto: "clothColor_blue1", traducao: "Ciano" },
        { texto: "clothColor_blue2", traducao: "Azul royal" },
        { texto: "clothColor_blue3", traducao: "Azul marinho" },
        { texto: "clothColor_gray1", traducao: "Cinza claro" },
        { texto: "clothColor_gray2", traducao: "Cinza" },
        { texto: "clothColor_heather", traducao: "Cinza escuro" },
        { texto: "clothColor_pastel_blue", traducao: "Azul pastel" },
        { texto: "clothColor_pastel_green", traducao: "Verde pastel" },
        { texto: "clothColor_pastel_orange", traducao: "Laranja pastel" },
        { texto: "clothColor_pastel_red", traducao: "Vermelho pastel" },
        { texto: "clothColor_pastel_yellow", traducao: "Amarelo pastel" },
        { texto: "clothColor_pink", traducao: "Rosa" },
        { texto: "clothColor_red", traducao: "Vermelho" },
        { texto: "clothColor_white", traducao: "Branco" },
        //Clothes
        { texto: "clothe_blazer_shirt", traducao: "Blazer com camiseta" },
        { texto: "clothe_blazer_sweater", traducao: "Blazer com suéter" },
        { texto: "clothe_collar_sweater", traducao: "Suéter" },
        { texto: "clothe_graphic_shirt", traducao: "Camiseta com estampa" },
        { texto: "clothe_hoodie", traducao: "Moletom" },
        { texto: "clothe_OVERALL", traducao: "Macacão" },
        { texto: "clothe_shirt_crewneck", traducao: "Camiseta gola redonda" },
        { texto: "clothe_shirt_scoopneck", traducao: "Camiseta gola canoa" },
        { texto: "clothe_shirt_vneck", traducao: "Camiseta gola V" },
        //Eyebrow
        { texto: "eyebrow_angry", traducao: "Sobrancelha 1" },
        { texto: "eyebrow_angry_natural", traducao: "Sobrancelha 2" },
        { texto: "eyebrow_none", traducao: "Sobrancelha 3" },
        { texto: "eyebrow_default_natural", traducao: "Sobrancelha 4" },
        { texto: "eyebrow_flat_natural", traducao: "Sobrancelha 5" },
        { texto: "eyebrow_raised_excited", traducao: "Sobrancelha 6" },
        { texto: "eyebrow_raised_excited_natural", traducao: "Sobrancelha 7" },
        { texto: "eyebrow_sad_concerned", traducao: "Sobrancelha 8" },
        { texto: "eyebrow_sad_concerned_natural", traducao: "Sobrancelha 9" },
        { texto: "eyebrow_unibrow_natural", traducao: "Sobrancelha 10" },
        { texto: "eyebrow_updown", traducao: "Sobrancelha 11" },
        { texto: "eyebrow_updown_natural", traducao: "Sobrancelha 12" },
        //Eyes
        { texto: "eyes_close", traducao: "Fechados" },
        { texto: "eyes_cry", traducao: "Chorando" },
        { texto: "eyes_none", traducao: "Normal" },
        { texto: "eyes_dizzy", traducao: "Morto" },
        { texto: "eyes_eyeroll", traducao: "Revirando" },
        { texto: "eyes_happy", traducao: "Feliz" },
        { texto: "eyes_hearts", traducao: "Apaixonado" },
        { texto: "eyes_side", traducao: "De lado" },
        { texto: "eyes_squint", traducao: "Semiaberto" },
        { texto: "eyes_surprised", traducao: "Surpreso" },
        { texto: "eyes_wink", traducao: "Piscada 1" },
        { texto: "eyes_winkwacky", traducao: "Piscada 2" },
        //FacialHairColor
        { texto: "facialHairColor_auburn", traducao: "Ruivo" },
        { texto: "facialHairColor_black", traducao: "Bigode preto" },
        { texto: "facialHairColor_blonde", traducao: "Louro" },
        { texto: "facialHairColor_blonde_golden", traducao: "Louro Claro" },
        { texto: "facialHairColor_brown", traducao: "Marrom" },
        { texto: "facialHairColor_brown_dark", traducao: "Marrom Escuro" },
        { texto: "facialHairColor_pastel_pink", traducao: "Platinado" },
        // { texto: "facialHairColor_platinum", traducao: "" },
        { texto: "facialHairColor_red", traducao: "Vermelho" },
        { texto: "facialHairColor_silver_red", traducao: "Rosa" },
        //FacialHair
        { texto: "facialHair_BLANK", traducao: "Nenhuma" },
        { texto: "facialHair_beard_medium", traducao: "Barba Média" },
        { texto: "facialHair_beard_light", traducao: "Barba Curta" },
        { texto: "facialHair_beard_magestic", traducao: "Barba Longa" },
        { texto: "facialHair_moustache_fancy", traducao: "Bigode" },
        { texto: "facialHair_moustache_magnum", traducao: "Bigode Cheio" },
        //Graphic 
        { texto: "graphic_bat", traducao: "Morcego" },
        { texto: "graphic_cumbia", traducao: "Cumbia" },
        // { texto: "graphic_ deer", traducao: "" },
        { texto: "graphic_diamond", traducao: "Diamante" },
        { texto: "graphic_hola", traducao: "Hola!" },
        { texto: "graphic_pizza", traducao: "Pizza" },
        { texto: "graphic_resist", traducao: "Resist!" },
        { texto: "graphic_selena", traducao: "Selena" },
        { texto: "graphic_bear", traducao: "Urso" },
        { texto: "graphic_skulloutline", traducao: "Caveira 1" },
        { texto: "graphic_skull", traducao: "Caveira 2" },
        //HairColor 
        { texto: "hairColor_aurburn", traducao: "Ruivo" },
        { texto: "hairColor_black", traducao: "Preto" },
        { texto: "hairColor_blonde", traducao: "Louro" },
        { texto: "hairColor_blondegolden", traducao: "Louro Claro" },
        { texto: "hairColor_brown", traducao: "Marrom" },
        { texto: "hairColor_browndark", traducao: "Marrom Escuro" },
        { texto: "hairColor_pastelpink", traducao: "Rosa" },
        { texto: "hairColor_platinum", traducao: "Platinado" },
        { texto: "hairColor_red", traducao: "Vermelho" },
        { texto: "hairColor_silvergray", traducao: "Cinza" },
        //HatColor
        { texto: "hatColor_black", traducao: "Preto" },
        { texto: "hatColor_blue01", traducao: "Ciano" },
        { texto: "hatColor_blue02", traducao: "Azul royal" },
        { texto: "hatColor_blue03", traducao: "Azul marinho" },
        { texto: "hatColor_gray01", traducao: "Cinza claro" },
        { texto: "hatColor_gray02", traducao: "Cinza" },
        { texto: "hatColor_heather", traducao: "Cinza escuro" },
        { texto: "hatColor_pastel_blue", traducao: "Azul pastel" },
        { texto: "hatColor_pastel_green", traducao: "Verde pastel" },
        { texto: "hatColor_pastel_orange", traducao: "Laranja pastel" },
        { texto: "hatColor_pastel_red", traducao: "Vermelho pastel" },
        { texto: "hatColor_pastel_yellow", traducao: "Amarelo pastel" },
        { texto: "hatColor_pink", traducao: "Rosa" },
        { texto: "hatColor_red", traducao: "Vermelho" },
        { texto: "hatColor_white", traducao: "Branco" },
        //Mouth 
        { texto: "mouth_concerened", traducao: "Preocupada" },
        { texto: "mouth_none", traducao: "Normal" },
        { texto: "mouth_disbelief", traducao: "Surpresa" },
        { texto: "mouth_eating", traducao: "Comendo" },
        { texto: "mouth_grimface", traducao: "Sorriso forçado" },
        { texto: "mouth_sad", traducao: "Triste" },
        { texto: "mouth_scream_open", traducao: "Queixo caído" },
        { texto: "mouth_serious", traducao: "Séria" },
        { texto: "mouth_smile", traducao: "Sorriso" },
        { texto: "mouth_tongue", traducao: "Língua para fora" },
        { texto: "mouth_twinkle", traducao: "Sorriso tímido" },
        { texto: "mouth_vomit", traducao: "Vômito" },
        //Skin
        { texto: "skin_tanned", traducao: "Bronzeada" },
        { texto: "skin_yellow", traducao: "Amarela" },
        { texto: "skin_pale", traducao: "Pálida" },
        { texto: "skin_light", traducao: "Branca" },
        { texto: "skin_brown", traducao: "Marrom" },
        { texto: "skin_dark_brown", traducao: "Marrom Escura" },
        { texto: "skin_black", traducao: "Preta" },
        //Top 
        { texto: "tops_no_hair", traducao: "Careca" },
        { texto: "tops_eyepatch", traducao: "Tapa olho" },
        { texto: "tops_hat", traducao: "Chapéu" },
        { texto: "tops_hijab", traducao: "Hijabe" },
        { texto: "tops_turban", traducao: "Turbante" },
        { texto: "tops_winter_hat1", traducao: "Touca 1" },
        { texto: "tops_winter_hat2", traducao: "Touca 2" },
        { texto: "tops_winter_hat3", traducao: "Touca 3" },
        { texto: "tops_winter_hat4", traducao: "Touca 4" },
        { texto: "tops_longhair_bighair", traducao: "Cabelo longo ondulado" },
        { texto: "tops_longhair_bob", traducao: "Cabelo Chanel" },
        { texto: "tops_longhair_bun", traducao: "Coque" },
        { texto: "tops_longhair_curly", traducao: "Cabelo Volumoso" },
        { texto: "tops_longhair_curvy", traducao: "Cabelo Ondulado com franja" },
        { texto: "tops_longhair_dreads", traducao: "Dread longo" },
        { texto: "tops_longhair_frida", traducao: "Frida" },
        { texto: "tops_longhair_fro", traducao: "Cabelo Black Power" },
        { texto: "tops_longhair_froband", traducao: "Cabelo Black Power com faixa" },
        { texto: "tops_longhair_nottoolong", traducao: "Cabelo Curto franja lateral" },
        { texto: "tops_longhairs_havedsides", traducao: "Cabelo longo topete" },
        { texto: "tops_longhair_miawallace", traducao: "Cabelo Curto franja" },
        { texto: "tops_longhair_straight", traducao: "Cabelo longo liso 1" },
        { texto: "tops_longhair_straight2", traducao: "Cabelo longo liso 2" },
        { texto: "tops_longhair_straightstrand", traducao: "Cabelo longo liso 3" },
        { texto: "tops_shorthair_dreads01", traducao: "Dread curto" },
        { texto: "tops_shorthair_dreads02", traducao: "Dread médio" },
        { texto: "tops_shorthair_frizzle", traducao: "Topete" },
        { texto: "tops_shorthair_shaggymullet", traducao: "Mullet" },
        { texto: "tops_shorthair_shortcurly", traducao: "Cabelo curto 1" },
        { texto: "tops_shorthair_shortflat", traducao: "Cabelo curto 2" },
        { texto: "tops_shorthair_shortround", traducao: "Cabelo curto 3" },
        { texto: "tops_shorthair_shortwaved", traducao: "Cabelo curto 4" },
        { texto: "tops_shorthair_sides", traducao: "Calvo de cria" },
        { texto: "tops_shorthair_thecaesar", traducao: "Raspado" },
        { texto: "tops_shorthair_thecaesarsidepart", traducao: "Chavoso" }
    ]

    static translate(texto: string): string {
        let item = this.traducoes.find(x => x.texto == texto);
        if (item && item.traducao != "")
            return item.traducao;
        return texto;
    }
}
