name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm install -g angular-cli-ghpages
        npm run ng -- build --base-href /https://shivam1410.github.io/fangpenlin-avataaars-generator-angular/
        ls
        cd public
        ls
      env:
        CI: true

